inherit_from: .rubocop_todo.yml

require: rubocop-ordered_methods

AllCops:
  TargetRubyVersion: 2.3

Metrics/BlockLength:
  Exclude:
    - spec/**/*

Naming/FileName:
  Exclude:
    - lib/rubocop-ordered_methods.rb
