name: CI

on:
  pull_request:
  push:
    branches:
      - master

jobs:
  main:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ruby:
          - "2.7"
          - "3.0"
          - "3.1"
          - "3.2"

    name: "Ruby ${{ matrix.ruby }}: run tests"
    steps:
      - uses: actions/checkout@v3
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: "${{ matrix.ruby }}"
          bundler-cache: true
      - run:  bundle exec rspec
